/**
 * VO-First 绝对时间轴 —— AUTO-GENERATED by scripts/gen-timeline.mjs，别手改。
 * 数据源：plan.md 的 ```timeline 块。要改：改 plan.md → `npm run gen`。
 *
 * 机制：录制态（?auto=1）播放整段原声 VO_FULL_SRC（一刀不切），每帧读
 * audio.currentTime，跨过 TIMELINE 某步的绝对起始秒就翻页 —— 零割裂、零漂移。
 * 多区间（补拍）：`?part=<id>` 选区间，整段音频 seek 到 start、播到 end 自动停。
 *
 * ⚠️ TIMELINE.length（6）必须 === 所有章节 narrations.length 之和（`npm run check` 会验）。
 */

/** true = 已由 plan.md 生成，App 的 auto 模式走整段原声驱动。 */
export const TIMELINE_GENERATED: boolean = true;

/** 每个全局 step 的绝对起始秒（升序，长度 = 全片总 step 数）。 */
export const TIMELINE: number[] = [
  /* 01 pipeline · step 0–5 */ 0, 3.576, 7.494, 12.578, 17.289, 20.812,
];

/** 整段口播音频（public/ 下相对路径，原片音轨一字节不改）。 */
export const VO_FULL_SRC = "audio/voiceover.wav";
/** ffprobe 实测整段时长（秒）。 */
export const VO_FULL_DURATION = 25.06779166666667;

export interface PartDef {
  id: string;
  /** 区间标签（AutoStartGate / 开发态 HUD 显示）。 */
  label: string;
  /** 绝对起播秒。 */
  start: number;
  /** 绝对停止秒 —— 播到这里自动暂停，录屏可以停了。 */
  end: number;
  /** 本区间第一个全局 step 下标（TIMELINE 的索引）。 */
  firstStep: number;
  /** 本区间最后一个全局 step 下标。 */
  lastStep: number;
}

export const PARTS: Record<string, PartDef> = {
  "full": {
    id: "full",
    label: "全片",
    start: 0,
    end: 25.06779166666667,
    firstStep: 0,
    lastStep: 5,
  },
};

/** 从 URL 读 `?part=<id>`；缺省 / 未知 id = 第一个区间。 */
export function readPart(): PartDef {
  const ids = Object.keys(PARTS);
  const first =
    ids.length > 0
      ? PARTS[ids[0]!]!
      : {
          id: "full",
          label: "全片",
          start: 0,
          end: VO_FULL_DURATION,
          firstStep: 0,
          lastStep: Math.max(0, TIMELINE.length - 1),
        };
  if (typeof window === "undefined") return first;
  const q = new URLSearchParams(window.location.search).get("part");
  if (!q) return first;
  const hit = PARTS[q];
  if (!hit) {
    console.warn(`unknown ?part=${q} — falling back to "${first.id}"`);
    return first;
  }
  return hit;
}

/** 把绝对秒格式化成 `m:ss.f`，开发态标注用。 */
export function fmtAbs(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = sec - m * 60;
  return `${m}:${s.toFixed(1).padStart(4, "0")}`;
}
